version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "digitalden-front-end"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-172g97ny9dr1x"
s3_prefix = "digitalden-front-end"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
